name: NBomber Performance Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nbomber-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run NBomber performance tests
      run: dotnet run --project AE_extensive_project.PerformanceTests.csproj

    - name: Upload NBomber reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: nbomber-reports
        path: bomber_reports/